# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPUEtWMXVHSlQ3TmXf7WGRhrUPeOnIRG
"""

print("hello from collab")

n = 10
fact = 1
for i in range(1, n + 1):
    fact = fact * i
print(f"factorial of {n} = {fact}")

a, b = 0, 1
result = []
for _ in range(n):
    result.append(a)
    next_num = a + b
    a = b
    b = next_num
print(' '.join(map(str, result)))

class Student:
    def __init__(self, name, roll, marks):
        self.name = name
        self.roll = roll
        self.marks = marks

s1 = Student("John", 101, 'excellent')

print(f"Name: {s1.name}")
print(f"Roll: {s1.roll}")
print(f"Marks: {s1.marks}")